//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamesControl.Web
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Contexto : DbContext
    {
        public Contexto()
            : base("name=Contexto")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tbarbitro> tbarbitro { get; set; }
        public virtual DbSet<tbatributoestatistica> tbatributoestatistica { get; set; }
        public virtual DbSet<tbcidade> tbcidade { get; set; }
        public virtual DbSet<tbestatisticaatributo> tbestatisticaatributo { get; set; }
        public virtual DbSet<tbestatisticajogo> tbestatisticajogo { get; set; }
        public virtual DbSet<tbjogador> tbjogador { get; set; }
        public virtual DbSet<tbjogo> tbjogo { get; set; }
        public virtual DbSet<tbjogostatus> tbjogostatus { get; set; }
        public virtual DbSet<tbPerfil> tbPerfil { get; set; }
        public virtual DbSet<tbtime> tbtime { get; set; }
        public virtual DbSet<tbusuario> tbusuario { get; set; }
        public virtual DbSet<tbusuariostatus> tbusuariostatus { get; set; }
    }
}
