//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamesControl.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbArbitro
    {
        public tbArbitro()
        {
            this.tbJogo = new HashSet<tbJogo>();
        }
    
        public int arbitroId { get; set; }
        public Nullable<int> usuarioId { get; set; }
    
        public virtual tbUsuario tbUsuario { get; set; }
        public virtual ICollection<tbJogo> tbJogo { get; set; }
    }
}
