//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamesControl.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbAtributoEstatistica
    {
        public tbAtributoEstatistica()
        {
            this.tbEstatisticaJogoJogadorTime = new HashSet<tbEstatisticaJogoJogadorTime>();
        }
    
        public int atributoEstatisticaId { get; set; }
        public string atributoEstatisticaDescricao { get; set; }
    
        public virtual ICollection<tbEstatisticaJogoJogadorTime> tbEstatisticaJogoJogadorTime { get; set; }
    }
}
