//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamesControl.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbCampeonato
    {
        public tbCampeonato()
        {
            this.tbjogo = new HashSet<tbjogo>();
        }
    
        public int campeonatoId { get; set; }
        public string campeonatoNome { get; set; }
    
        public virtual ICollection<tbjogo> tbjogo { get; set; }
    }
}
