//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamesControl.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbcidade
    {
        public tbcidade()
        {
            this.tbjogador = new HashSet<tbjogador>();
            this.tbtime = new HashSet<tbtime>();
        }
    
        public int cidadeId { get; set; }
        public string cidadeNome { get; set; }
    
        public virtual ICollection<tbjogador> tbjogador { get; set; }
        public virtual ICollection<tbtime> tbtime { get; set; }
    }
}
