//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamesControl.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbCidade
    {
        public tbCidade()
        {
            this.tbTime = new HashSet<tbTime>();
            this.tbJogador = new HashSet<tbJogador>();
        }
    
        public int cidadeId { get; set; }
        public string cidadeNome { get; set; }
    
        public virtual ICollection<tbTime> tbTime { get; set; }
        public virtual ICollection<tbJogador> tbJogador { get; set; }
    }
}
