//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamesControl.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbestatisticajogo
    {
        public int jogoId { get; set; }
        public int atributoEstatisticaId { get; set; }
        public int jogadorId { get; set; }
        public int estatisticaJogoQuantidade { get; set; }
    
        public virtual tbatributoestatistica tbatributoestatistica { get; set; }
        public virtual tbjogador tbjogador { get; set; }
        public virtual tbjogo tbjogo { get; set; }
    }
}
