//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamesControl.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbEstatisticaJogoJogadorTime
    {
        public int jogoId { get; set; }
        public int timeId { get; set; }
        public int jogadorId { get; set; }
        public int atributoEstatisticaId { get; set; }
        public int estatisticaJogoQuantidade { get; set; }
    
        public virtual tbAtributoEstatistica tbAtributoEstatistica { get; set; }
        public virtual tbJogoJogadorTime tbJogoJogadorTime { get; set; }
    }
}
