//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamesControl.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbestatisticaatributo
    {
        public int estatisticaJogoId { get; set; }
        public int atributoEstatisticaId { get; set; }
        public int estatisticaAtributoQuantidade { get; set; }
    }
}
