//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamesControl.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbjogador
    {
        public tbjogador()
        {
            this.tbestatisticajogo = new HashSet<tbestatisticajogo>();
        }
    
        public int jogadorId { get; set; }
        public System.DateTime jogadorDataNascimento { get; set; }
        public int cidadeId { get; set; }
        public Nullable<int> usuarioId { get; set; }
    
        public virtual tbcidade tbcidade { get; set; }
        public virtual ICollection<tbestatisticajogo> tbestatisticajogo { get; set; }
        public virtual tbusuario tbusuario { get; set; }
    }
}
