//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamesControl.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbJogador
    {
        public tbJogador()
        {
            this.tbEstatisticaJogoJogadorTime = new HashSet<tbEstatisticaJogoJogadorTime>();
            this.tbJogoJogadorTime = new HashSet<tbJogoJogadorTime>();
            this.tbTime = new HashSet<tbTime>();
        }
    
        public int jogadorId { get; set; }
        public System.DateTime jogadorDataNascimento { get; set; }
        public int cidadeId { get; set; }
        public int usuarioId { get; set; }
        public bool jogadorAtivo { get; set; }
    
        public virtual tbCidade tbCidade { get; set; }
        public virtual ICollection<tbEstatisticaJogoJogadorTime> tbEstatisticaJogoJogadorTime { get; set; }
        public virtual ICollection<tbJogoJogadorTime> tbJogoJogadorTime { get; set; }
        public virtual tbUsuario tbUsuario { get; set; }
        public virtual ICollection<tbTime> tbTime { get; set; }
    }
}
