//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamesControl.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbjogo
    {
        public tbjogo()
        {
            this.tbestatisticajogo = new HashSet<tbestatisticajogo>();
            this.tbJogoJogadorTime = new HashSet<tbJogoJogadorTime>();
            this.tbarbitro = new HashSet<tbarbitro>();
        }
    
        public int jogoId { get; set; }
        public int campeonatoId { get; set; }
        public int timeCasaId { get; set; }
        public int timeVisitanteId { get; set; }
        public System.DateTime jogoData { get; set; }
        public Nullable<int> jogoStatusId { get; set; }
        public Nullable<int> jogoPontuacaoCasa { get; set; }
        public Nullable<int> jogoPontuacaoVisitante { get; set; }
    
        public virtual tbCampeonato tbCampeonato { get; set; }
        public virtual ICollection<tbestatisticajogo> tbestatisticajogo { get; set; }
        public virtual ICollection<tbJogoJogadorTime> tbJogoJogadorTime { get; set; }
        public virtual tbjogostatus tbjogostatus { get; set; }
        public virtual tbtime tbtime { get; set; }
        public virtual tbtime tbtime1 { get; set; }
        public virtual ICollection<tbarbitro> tbarbitro { get; set; }
    }
}
