//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamesControl.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbJogo
    {
        public tbJogo()
        {
            this.tbJogoJogadorTime = new HashSet<tbJogoJogadorTime>();
            this.tbArbitro = new HashSet<tbArbitro>();
        }
    
        public int jogoId { get; set; }
        public int campeonatoId { get; set; }
        public int timeCasaId { get; set; }
        public int timeVisitanteId { get; set; }
        public System.DateTime jogoData { get; set; }
        public Nullable<int> jogoStatusId { get; set; }
        public Nullable<int> jogoPontuacaoCasa { get; set; }
        public Nullable<int> jogoPontuacaoVisitante { get; set; }
    
        public virtual tbCampeonato tbCampeonato { get; set; }
        public virtual ICollection<tbJogoJogadorTime> tbJogoJogadorTime { get; set; }
        public virtual tbJogoStatus tbJogoStatus { get; set; }
        public virtual tbTime tbTime { get; set; }
        public virtual tbTime tbTime1 { get; set; }
        public virtual ICollection<tbArbitro> tbArbitro { get; set; }
    }
}
