//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamesControl.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbJogoJogadorTime
    {
        public tbJogoJogadorTime()
        {
            this.tbEstatisticaJogoJogadorTime = new HashSet<tbEstatisticaJogoJogadorTime>();
        }
    
        public int jogoId { get; set; }
        public int jogadorId { get; set; }
        public int timeId { get; set; }
    
        public virtual ICollection<tbEstatisticaJogoJogadorTime> tbEstatisticaJogoJogadorTime { get; set; }
        public virtual tbJogador tbJogador { get; set; }
        public virtual tbJogo tbJogo { get; set; }
        public virtual tbTime tbTime { get; set; }
    }
}
