//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamesControl.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbTime
    {
        public tbTime()
        {
            this.tbJogo = new HashSet<tbJogo>();
            this.tbJogo1 = new HashSet<tbJogo>();
            this.tbJogoJogadorTime = new HashSet<tbJogoJogadorTime>();
            this.tbJogador = new HashSet<tbJogador>();
        }
    
        public int timeId { get; set; }
        public string timeNome { get; set; }
        public string timeCaminhoLogo { get; set; }
        public int cidadeId { get; set; }
    
        public virtual tbCidade tbCidade { get; set; }
        public virtual ICollection<tbJogo> tbJogo { get; set; }
        public virtual ICollection<tbJogo> tbJogo1 { get; set; }
        public virtual ICollection<tbJogoJogadorTime> tbJogoJogadorTime { get; set; }
        public virtual ICollection<tbJogador> tbJogador { get; set; }
    }
}
