//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamesControl.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbusuariostatus
    {
        public tbusuariostatus()
        {
            this.tbusuario = new HashSet<tbusuario>();
        }
    
        public int usuarioStatusId { get; set; }
        public string usuarioStatusDescricao { get; set; }
    
        public virtual ICollection<tbusuario> tbusuario { get; set; }
    }
}
