//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamesControl.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbUsuario
    {
        public tbUsuario()
        {
            this.tbArbitro = new HashSet<tbArbitro>();
            this.tbJogador = new HashSet<tbJogador>();
            this.tbPerfil = new HashSet<tbPerfil>();
        }
    
        public int usuarioId { get; set; }
        public string usuarioEmail { get; set; }
        public string usuarioNome { get; set; }
        public string usuarioSenha { get; set; }
        public string usuarioTelefone { get; set; }
        public int usuarioStatusId { get; set; }
        public int perfilId { get; set; }
        public string usuarioFoto { get; set; }
        public Nullable<System.DateTime> usuarioDataSolicitacao { get; set; }
    
        public virtual ICollection<tbArbitro> tbArbitro { get; set; }
        public virtual ICollection<tbJogador> tbJogador { get; set; }
        public virtual tbUsuarioStatus tbUsuarioStatus { get; set; }
        public virtual ICollection<tbPerfil> tbPerfil { get; set; }
    }
}
